sudo:required
services:
  - docker

before_install:
  - docker build -t eggjr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eggjr/react-test npm run test -- --coverage

after_success:
  - docker build -t eggjr/multi-client ./client
  - docker build -t eggjr/multi-nginx ./nginx
  - docker build -t eggjr/multi-server ./server
  - docker build -t eggjr/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to Dockerhub
  - docker push eggjr/multi-client
  - docker push eggjr/multi-nginx
  - docker push eggjr/multi-server
  - docker push eggjr/multi-worker